AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Static Website Hosting with IP-based access restriction'

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket (must be globally unique)

  AllowedIP:
    Type: String
    Description: IP address allowed to access the bucket (CIDR format, e.g., 203.0.113.0/32)
    AllowedPattern: '(\d{1,3}\.){3}\d{1,3}(/\d{1,2})?'

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Purpose
          Value: StaticWebsiteHosting

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowSpecificIPAccess
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${WebsiteBucket.Arn}/*'
            Condition:
              IpAddress:
                aws:SourceIp: !Ref AllowedIP

Outputs:
  WebsiteURL:
    Description: URL of the website
    Value: !GetAtt WebsiteBucket.WebsiteURL

  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref WebsiteBucket

  BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt WebsiteBucket.Arn
