import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "作品管理アプリケーション",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
    apple: '/favicon.ico', // 暫定的にfavicon.icoを使用
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: "作品管理",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden h-screen`}
      >
        {children}
      </body>
    </html>
  );
}